//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.27 at 04:28:50 PM PDT 
//


package com.mlb.qa.atb.model.schedule_pk;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mlb.qa.atb.model.schedule_pk package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mlb.qa.atb.model.schedule_pk
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchedulePk }
     * 
     */
    public SchedulePk createSchedulePk() {
        return new SchedulePk();
    }

    /**
     * Create an instance of {@link SchedulePk.QueryResults }
     * 
     */
    public SchedulePk.QueryResults createSchedulePkQueryResults() {
        return new SchedulePk.QueryResults();
    }

    /**
     * Create an instance of {@link SchedulePk.QueryResults.Row }
     * 
     */
    public SchedulePk.QueryResults.Row createSchedulePkQueryResultsRow() {
        return new SchedulePk.QueryResults.Row();
    }

}
