//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.27 at 04:28:50 PM PDT 
//


package com.mlb.qa.atb.model.schedule_pk;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryResults"
})
@XmlRootElement(name = "schedule_pk")
public class SchedulePk {

    @XmlElement(required = true)
    protected SchedulePk.QueryResults queryResults;

    /**
     * Gets the value of the queryResults property.
     * 
     * @return
     *     possible object is
     *     {@link SchedulePk.QueryResults }
     *     
     */
    public SchedulePk.QueryResults getQueryResults() {
        return queryResults;
    }

    /**
     * Sets the value of the queryResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedulePk.QueryResults }
     *     
     */
    public void setQueryResults(SchedulePk.QueryResults value) {
        this.queryResults = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class QueryResults {

        @XmlElement(required = true)
        protected SchedulePk.QueryResults.Row row;
        @XmlAttribute(name = "totalSize")
        protected Integer totalSize;
        @XmlAttribute(name = "created")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar created;

        /**
         * Gets the value of the row property.
         * 
         * @return
         *     possible object is
         *     {@link SchedulePk.QueryResults.Row }
         *     
         */
        public SchedulePk.QueryResults.Row getRow() {
            return row;
        }

        /**
         * Sets the value of the row property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchedulePk.QueryResults.Row }
         *     
         */
        public void setRow(SchedulePk.QueryResults.Row value) {
            this.row = value;
        }

        /**
         * Gets the value of the totalSize property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTotalSize() {
            return totalSize;
        }

        /**
         * Sets the value of the totalSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTotalSize(Integer value) {
            this.totalSize = value;
        }

        /**
         * Gets the value of the created property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreated() {
            return created;
        }

        /**
         * Sets the value of the created property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreated(XMLGregorianCalendar value) {
            this.created = value;
        }


               @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Row {

            @XmlAttribute(name = "game_pk")
            protected Integer gamePk;
            @XmlAttribute(name = "game_id")
            protected String gameId;
            @XmlAttribute(name = "gd_game_id")
            protected String gdGameId;
            @XmlAttribute(name = "venue_id")
            protected Integer venueId;
            @XmlAttribute(name = "venue_name")
            protected String venueName;
            @XmlAttribute(name = "venue_city")
            protected String venueCity;
            @XmlAttribute(name = "game_time")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar gameTime;
            @XmlAttribute(name = "game_time_et")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar gameTimeEt;
            @XmlAttribute(name = "game_time_local")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar gameTimeLocal;
            @XmlAttribute(name = "time_zone_local")
            protected String timeZoneLocal;
            @XmlAttribute(name = "local_offset")
            protected Integer localOffset;
            @XmlAttribute(name = "game_time_home")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar gameTimeHome;
            @XmlAttribute(name = "time_zone_home")
            protected String timeZoneHome;
            @XmlAttribute(name = "game_time_away")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar gameTimeAway;
            @XmlAttribute(name = "time_zone_away")
            protected String timeZoneAway;
            @XmlAttribute(name = "game_time_tbd_sw")
            protected String gameTimeTbdSw;
            @XmlAttribute(name = "game_status_ind")
            protected String gameStatusInd;
            @XmlAttribute(name = "start_time")
            protected String startTime;
            @XmlAttribute(name = "home_team_id")
            protected Integer homeTeamId;
            @XmlAttribute(name = "away_team_id")
            protected Integer awayTeamId;
            @XmlAttribute(name = "home_name_city")
            protected String homeNameCity;
            @XmlAttribute(name = "away_name_city")
            protected String awayNameCity;
            @XmlAttribute(name = "home_name_full")
            protected String homeNameFull;
            @XmlAttribute(name = "away_name_full")
            protected String awayNameFull;
            @XmlAttribute(name = "home_name_abbrev")
            protected String homeNameAbbrev;
            @XmlAttribute(name = "away_name_abbrev")
            protected String awayNameAbbrev;
            @XmlAttribute(name = "home_league_id")
            protected Integer homeLeagueId;
            @XmlAttribute(name = "away_league_id")
            protected Integer awayLeagueId;
            @XmlAttribute(name = "home_league")
            protected String homeLeague;
            @XmlAttribute(name = "away_league")
            protected String awayLeague;
            @XmlAttribute(name = "home_sport_id")
            protected Integer homeSportId;
            @XmlAttribute(name = "away_sport_id")
            protected Integer awaySportId;
            @XmlAttribute(name = "home_sport_code")
            protected String homeSportCode;
            @XmlAttribute(name = "away_sport_code")
            protected String awaySportCode;
            @XmlAttribute(name = "game_type")
            protected String gameType;
            @XmlAttribute(name = "home_score")
            protected String homeScore;
            @XmlAttribute(name = "away_score")
            protected String awayScore;
            @XmlAttribute(name = "umpire_hp")
            protected String umpireHp;
            @XmlAttribute(name = "umpire_hp_name")
            protected String umpireHpName;
            @XmlAttribute(name = "umpire_1b")
            protected String umpire1B;
            @XmlAttribute(name = "umpire_1b_name")
            protected String umpire1BName;
            @XmlAttribute(name = "umpire_2b")
            protected String umpire2B;
            @XmlAttribute(name = "umpire_2b_name")
            protected String umpire2BName;
            @XmlAttribute(name = "umpire_3b")
            protected String umpire3B;
            @XmlAttribute(name = "umpire_3b_name")
            protected String umpire3BName;
            @XmlAttribute(name = "umpire_l")
            protected String umpireL;
            @XmlAttribute(name = "umpire_l_name")
            protected String umpireLName;
            @XmlAttribute(name = "umpire_r")
            protected String umpireR;
            @XmlAttribute(name = "umpire_r_name")
            protected String umpireRName;
            @XmlAttribute(name = "official_scorer")
            protected String officialScorer;
            @XmlAttribute(name = "official_scorer_name")
            protected String officialScorerName;
            @XmlAttribute(name = "venue_type_cd")
            protected String venueTypeCd;
            @XmlAttribute(name = "venue_type")
            protected String venueType;
            @XmlAttribute(name = "sky")
            protected String sky;
            @XmlAttribute(name = "temperature")
            protected String temperature;
            @XmlAttribute(name = "wind_speed")
            protected String windSpeed;
            @XmlAttribute(name = "wind_direction")
            protected String windDirection;

            /**
             * Gets the value of the gamePk property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGamePk() {
                return gamePk;
            }

            /**
             * Sets the value of the gamePk property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGamePk(Integer value) {
                this.gamePk = value;
            }

            /**
             * Gets the value of the gameId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGameId() {
                return gameId;
            }

            /**
             * Sets the value of the gameId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGameId(String value) {
                this.gameId = value;
            }

            /**
             * Gets the value of the gdGameId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGdGameId() {
                return gdGameId;
            }

            /**
             * Sets the value of the gdGameId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGdGameId(String value) {
                this.gdGameId = value;
            }

            /**
             * Gets the value of the venueId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getVenueId() {
                return venueId;
            }

            /**
             * Sets the value of the venueId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setVenueId(Integer value) {
                this.venueId = value;
            }

            /**
             * Gets the value of the venueName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVenueName() {
                return venueName;
            }

            /**
             * Sets the value of the venueName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVenueName(String value) {
                this.venueName = value;
            }

            /**
             * Gets the value of the venueCity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVenueCity() {
                return venueCity;
            }

            /**
             * Sets the value of the venueCity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVenueCity(String value) {
                this.venueCity = value;
            }

            /**
             * Gets the value of the gameTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGameTime() {
                return gameTime;
            }

            /**
             * Sets the value of the gameTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGameTime(XMLGregorianCalendar value) {
                this.gameTime = value;
            }

            /**
             * Gets the value of the gameTimeEt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGameTimeEt() {
                return gameTimeEt;
            }

            /**
             * Sets the value of the gameTimeEt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGameTimeEt(XMLGregorianCalendar value) {
                this.gameTimeEt = value;
            }

            /**
             * Gets the value of the gameTimeLocal property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGameTimeLocal() {
                return gameTimeLocal;
            }

            /**
             * Sets the value of the gameTimeLocal property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGameTimeLocal(XMLGregorianCalendar value) {
                this.gameTimeLocal = value;
            }

            /**
             * Gets the value of the timeZoneLocal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeZoneLocal() {
                return timeZoneLocal;
            }

            /**
             * Sets the value of the timeZoneLocal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeZoneLocal(String value) {
                this.timeZoneLocal = value;
            }

            /**
             * Gets the value of the localOffset property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getLocalOffset() {
                return localOffset;
            }

            /**
             * Sets the value of the localOffset property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setLocalOffset(Integer value) {
                this.localOffset = value;
            }

            /**
             * Gets the value of the gameTimeHome property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGameTimeHome() {
                return gameTimeHome;
            }

            /**
             * Sets the value of the gameTimeHome property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGameTimeHome(XMLGregorianCalendar value) {
                this.gameTimeHome = value;
            }

            /**
             * Gets the value of the timeZoneHome property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeZoneHome() {
                return timeZoneHome;
            }

            /**
             * Sets the value of the timeZoneHome property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeZoneHome(String value) {
                this.timeZoneHome = value;
            }

            /**
             * Gets the value of the gameTimeAway property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGameTimeAway() {
                return gameTimeAway;
            }

            /**
             * Sets the value of the gameTimeAway property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGameTimeAway(XMLGregorianCalendar value) {
                this.gameTimeAway = value;
            }

            /**
             * Gets the value of the timeZoneAway property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeZoneAway() {
                return timeZoneAway;
            }

            /**
             * Sets the value of the timeZoneAway property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeZoneAway(String value) {
                this.timeZoneAway = value;
            }

            /**
             * Gets the value of the gameTimeTbdSw property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGameTimeTbdSw() {
                return gameTimeTbdSw;
            }

            /**
             * Sets the value of the gameTimeTbdSw property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGameTimeTbdSw(String value) {
                this.gameTimeTbdSw = value;
            }

            /**
             * Gets the value of the gameStatusInd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGameStatusInd() {
                return gameStatusInd;
            }

            /**
             * Sets the value of the gameStatusInd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGameStatusInd(String value) {
                this.gameStatusInd = value;
            }

            /**
             * Gets the value of the startTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartTime() {
                return startTime;
            }

            /**
             * Sets the value of the startTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartTime(String value) {
                this.startTime = value;
            }

            /**
             * Gets the value of the homeTeamId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHomeTeamId() {
                return homeTeamId;
            }

            /**
             * Sets the value of the homeTeamId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHomeTeamId(Integer value) {
                this.homeTeamId = value;
            }

            /**
             * Gets the value of the awayTeamId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getAwayTeamId() {
                return awayTeamId;
            }

            /**
             * Sets the value of the awayTeamId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setAwayTeamId(Integer value) {
                this.awayTeamId = value;
            }

            /**
             * Gets the value of the homeNameCity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHomeNameCity() {
                return homeNameCity;
            }

            /**
             * Sets the value of the homeNameCity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHomeNameCity(String value) {
                this.homeNameCity = value;
            }

            /**
             * Gets the value of the awayNameCity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAwayNameCity() {
                return awayNameCity;
            }

            /**
             * Sets the value of the awayNameCity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAwayNameCity(String value) {
                this.awayNameCity = value;
            }

            /**
             * Gets the value of the homeNameFull property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHomeNameFull() {
                return homeNameFull;
            }

            /**
             * Sets the value of the homeNameFull property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHomeNameFull(String value) {
                this.homeNameFull = value;
            }

            /**
             * Gets the value of the awayNameFull property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAwayNameFull() {
                return awayNameFull;
            }

            /**
             * Sets the value of the awayNameFull property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAwayNameFull(String value) {
                this.awayNameFull = value;
            }

            /**
             * Gets the value of the homeNameAbbrev property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHomeNameAbbrev() {
                return homeNameAbbrev;
            }

            /**
             * Sets the value of the homeNameAbbrev property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHomeNameAbbrev(String value) {
                this.homeNameAbbrev = value;
            }

            /**
             * Gets the value of the awayNameAbbrev property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAwayNameAbbrev() {
                return awayNameAbbrev;
            }

            /**
             * Sets the value of the awayNameAbbrev property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAwayNameAbbrev(String value) {
                this.awayNameAbbrev = value;
            }

            /**
             * Gets the value of the homeLeagueId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHomeLeagueId() {
                return homeLeagueId;
            }

            /**
             * Sets the value of the homeLeagueId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHomeLeagueId(Integer value) {
                this.homeLeagueId = value;
            }

            /**
             * Gets the value of the awayLeagueId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getAwayLeagueId() {
                return awayLeagueId;
            }

            /**
             * Sets the value of the awayLeagueId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setAwayLeagueId(Integer value) {
                this.awayLeagueId = value;
            }

            /**
             * Gets the value of the homeLeague property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHomeLeague() {
                return homeLeague;
            }

            /**
             * Sets the value of the homeLeague property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHomeLeague(String value) {
                this.homeLeague = value;
            }

            /**
             * Gets the value of the awayLeague property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAwayLeague() {
                return awayLeague;
            }

            /**
             * Sets the value of the awayLeague property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAwayLeague(String value) {
                this.awayLeague = value;
            }

            /**
             * Gets the value of the homeSportId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHomeSportId() {
                return homeSportId;
            }

            /**
             * Sets the value of the homeSportId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHomeSportId(Integer value) {
                this.homeSportId = value;
            }

            /**
             * Gets the value of the awaySportId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getAwaySportId() {
                return awaySportId;
            }

            /**
             * Sets the value of the awaySportId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setAwaySportId(Integer value) {
                this.awaySportId = value;
            }

            /**
             * Gets the value of the homeSportCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHomeSportCode() {
                return homeSportCode;
            }

            /**
             * Sets the value of the homeSportCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHomeSportCode(String value) {
                this.homeSportCode = value;
            }

            /**
             * Gets the value of the awaySportCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAwaySportCode() {
                return awaySportCode;
            }

            /**
             * Sets the value of the awaySportCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAwaySportCode(String value) {
                this.awaySportCode = value;
            }

            /**
             * Gets the value of the gameType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGameType() {
                return gameType;
            }

            /**
             * Sets the value of the gameType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGameType(String value) {
                this.gameType = value;
            }

            /**
             * Gets the value of the homeScore property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHomeScore() {
                return homeScore;
            }

            /**
             * Sets the value of the homeScore property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHomeScore(String value) {
                this.homeScore = value;
            }

            /**
             * Gets the value of the awayScore property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAwayScore() {
                return awayScore;
            }

            /**
             * Sets the value of the awayScore property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAwayScore(String value) {
                this.awayScore = value;
            }

            /**
             * Gets the value of the umpireHp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpireHp() {
                return umpireHp;
            }

            /**
             * Sets the value of the umpireHp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpireHp(String value) {
                this.umpireHp = value;
            }

            /**
             * Gets the value of the umpireHpName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpireHpName() {
                return umpireHpName;
            }

            /**
             * Sets the value of the umpireHpName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpireHpName(String value) {
                this.umpireHpName = value;
            }

            /**
             * Gets the value of the umpire1B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpire1B() {
                return umpire1B;
            }

            /**
             * Sets the value of the umpire1B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpire1B(String value) {
                this.umpire1B = value;
            }

            /**
             * Gets the value of the umpire1BName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpire1BName() {
                return umpire1BName;
            }

            /**
             * Sets the value of the umpire1BName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpire1BName(String value) {
                this.umpire1BName = value;
            }

            /**
             * Gets the value of the umpire2B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpire2B() {
                return umpire2B;
            }

            /**
             * Sets the value of the umpire2B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpire2B(String value) {
                this.umpire2B = value;
            }

            /**
             * Gets the value of the umpire2BName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpire2BName() {
                return umpire2BName;
            }

            /**
             * Sets the value of the umpire2BName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpire2BName(String value) {
                this.umpire2BName = value;
            }

            /**
             * Gets the value of the umpire3B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpire3B() {
                return umpire3B;
            }

            /**
             * Sets the value of the umpire3B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpire3B(String value) {
                this.umpire3B = value;
            }

            /**
             * Gets the value of the umpire3BName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpire3BName() {
                return umpire3BName;
            }

            /**
             * Sets the value of the umpire3BName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpire3BName(String value) {
                this.umpire3BName = value;
            }

            /**
             * Gets the value of the umpireL property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpireL() {
                return umpireL;
            }

            /**
             * Sets the value of the umpireL property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpireL(String value) {
                this.umpireL = value;
            }

            /**
             * Gets the value of the umpireLName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpireLName() {
                return umpireLName;
            }

            /**
             * Sets the value of the umpireLName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpireLName(String value) {
                this.umpireLName = value;
            }

            /**
             * Gets the value of the umpireR property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpireR() {
                return umpireR;
            }

            /**
             * Sets the value of the umpireR property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpireR(String value) {
                this.umpireR = value;
            }

            /**
             * Gets the value of the umpireRName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmpireRName() {
                return umpireRName;
            }

            /**
             * Sets the value of the umpireRName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmpireRName(String value) {
                this.umpireRName = value;
            }

            /**
             * Gets the value of the officialScorer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOfficialScorer() {
                return officialScorer;
            }

            /**
             * Sets the value of the officialScorer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOfficialScorer(String value) {
                this.officialScorer = value;
            }

            /**
             * Gets the value of the officialScorerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOfficialScorerName() {
                return officialScorerName;
            }

            /**
             * Sets the value of the officialScorerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOfficialScorerName(String value) {
                this.officialScorerName = value;
            }

            /**
             * Gets the value of the venueTypeCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVenueTypeCd() {
                return venueTypeCd;
            }

            /**
             * Sets the value of the venueTypeCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVenueTypeCd(String value) {
                this.venueTypeCd = value;
            }

            /**
             * Gets the value of the venueType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVenueType() {
                return venueType;
            }

            /**
             * Sets the value of the venueType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVenueType(String value) {
                this.venueType = value;
            }

            /**
             * Gets the value of the sky property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSky() {
                return sky;
            }

            /**
             * Sets the value of the sky property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSky(String value) {
                this.sky = value;
            }

            /**
             * Gets the value of the temperature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTemperature() {
                return temperature;
            }

            /**
             * Sets the value of the temperature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTemperature(String value) {
                this.temperature = value;
            }

            /**
             * Gets the value of the windSpeed property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWindSpeed() {
                return windSpeed;
            }

            /**
             * Sets the value of the windSpeed property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWindSpeed(String value) {
                this.windSpeed = value;
            }

            /**
             * Gets the value of the windDirection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWindDirection() {
                return windDirection;
            }

            /**
             * Sets the value of the windDirection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWindDirection(String value) {
                this.windDirection = value;
            }

        }

    }

}
